#+TITLE: The appeal of upstream: why my dotfiles commits are dwindling
#+TAGS: Tech Emacs "Window managers"


As I dive into my senior year at RIT, I have a lot less time to explore software
configurations: new plugins, workflows, and the software that accompanies them,
all take too much time to learn and incorporate with my current workflow.

As I’ve written before: Spacemacs does 90% of what I want to do, but despite
that, I have and maintain my own Emacs config.

On the maintenance end… I rarely have time for that as well. My KDE+Xmonad
config fell apart with KDE Plasma 5.13. Around 95% of the time, Plasma windows
immediately disappear after popping up, making the setup unusable.

There’s value in a project that others are invested in. If something breaks, you
aren’t on your own to try and fix it.

While these projects have opinions, a minor change to workflow may be worth the
security the new workflow brings.

[[https://gogs.jibby.org/jhb2345/dotfiles/commit/443c94b87e228e43dbe2a77cecb406d8bb48f60b][I’ve moved to Spacemacs]] for the time being. [[https://github.com/danielgreve/bspwm-kde-session][My new window manager + DE setup]]
isn’t nearly as functionally pure, but it hasn’t broken with the newest KDE.

Knowing the tools I have aren’t going to explode on me with a new update has
been worth the transition. Maybe I’ll get sick of the new bindings and
paradigms, but for the time being, I have a much more reliable box.
