#+TITLE: I’m not on my phone much anymore.
#+TAGS: Life


There are plenty of blog posts already, discussing the toxic effects of social
media and electronic communication integrating themselves in our lives.

But, meh, I’m gonna talk about it anyway. I write for myself. I hope so, at
least. Otherwise, I’m disappointing someone or some group of people out there.

** Social media

Blogging is shouting to the world too, I guess. But this is my corner of the
world, where I can do or say what I want. I’m not spamming it anywhere, or
desperately trying to get on someone’s feed. If you wanna read it, read it.
Again, writing for myself. Sometimes to communicate information or life events,
but I don’t feel the pressure. I don’t feel judgmental eyes: instead, I only
feel eyes that cared enough to seek out my little corner of the internet.

Maybe that’s the big difference between blogging and social media. It’s not
trying to be social in the same way. Sure, you’re putting your writing on
display, but not in an attempt to connect with others over it. It can be
therapeutic, for the sharing of knowledge, or to spark controversy, but rarely
does it seem to consist of pointless mudslinging or constant life updates. No
dopamine-inducing like button to be seen. Just a handful of anonymous strangers
pinging the site’s RSS feed. Or not. I don’t know.

It’s a weird balance between a diary and a public forum. But it has the benefits
of both, in my opinion.

** Phones

I’ve had a smartphone all through college, and most recently, a smart watch that
pushes messages to my wrist. While it’s great to hear from friends across the
U.S., I’ve never felt more lonely than when I was looking at the lack of
notifications on my phone. If it catches me during a slump, it makes me feel
like something’s wrong with me.

And it really shouldn’t.

While humans are social creatures, I believe having an independent set of
hobbies and interests is essential for maintaining a relative amount of
self-satisfaction. For better or for worse, you’re stuck with you, so you might
as well get to know them! You’re always gonna be there for you, to cheer you up,
so you best get to learning how.

Phones make communicating with those we want to communicate with (and those we
don’t) easier than ever. But the dominating platforms want you on the platform
as much as possible of course. That’s why you get everything from push
notifications for Instagram stories, to the “Say hello to your new friend”
default message on Facebook. Engage, speak with your friend, check up on them!
More face time means more advertisement value.

But, to many, it also means more anxiety. Less self-assurance. Why is my phone
quiet sometimes? Is it because I don’t have friends, or don’t have enough?

Many of my friends have disabled a majority of non-essential push notifications
on their phones. I don’t really need Instagram story updates: when I get around
to seeing it, I’ll see it. If I don’t see it before then, I don’t really care.

When I’m not constantly getting (or awaiting) pings, I find more things to do
with the environment around me. Since they stimulate more senses than a screen
and speaker can offer, they feel more meaningful and engaging.

And the smart watch makes it worse, honestly. I got this thing to track my
fitness, and skip songs while I’m in the shower.

I’ve tried to limit my phone use to a handful of things:

+ Keep in touch with long distance friends
+ Organize meetups with nearby friends
+ One-off messages, or good discussions to log
+ Meet new people

** What Bridges these gaps?

Instagram is still going strong, despite Facebook losing some popularity with
younger users. Privacy issues aside, I’d say there’s a couple fundamental
differences with the platforms.

Yes, Instagram is about pictures. But it’s more about how you interact with
them.

You can’t share things you see the same way you can on Facebook. Instead of
adding something else to your feed, you add it to your story. Stories are heavy
doses of what one person or account is doing at a recent time. So seeing how
someone’s day went, while it’s not directly a two way street, feels more
personal than seeing how 200+ of your closest friends are doing, all blended
together.

Sure, you don’t have to use Facebook’s news feed, but that’s the default, and at
the end of the day, the defaults are all that matter. People will be pushed to
use the platform this way, and the consequences of doing so are pushed as well.

What’s the alternative to sharing something on your story? Well, you can message
people directly, including a link to the cool thing you found. Opening up
personal messages is a much more comforting, personal experience, when we’re
stuck in a world where 7 billion voices are all trying to be heard. A personal
message is a greater chance that one of those individuals cares about you enough
to send a thing to you, personally.

That’s not always the case, but it’s a nice thought.

There’s another platform that further encourages this nice thought. Snapchat.

While the illusion of privacy that Snapchat brings is nice as well, the default
usage of the platform is person-to-person communication. Not just that, but
communication through images, where it’s much easier to convey tone,
individuality, and personality. Context lost on text is at times recovered with
an accompanying image.

Again, this platform is not exclusively one-to-one: it has a story platform, as
well as group chats. But, the most common way to respond to a story event is
with a personal message, once again opening that channel of individual
communication.

** Where to go from here?

I really like the idea of one-to-one communication, or at least heavily “opt-in”
options for catching up on another person’s life events. Most of my social media
use in personal, in groups of friends, or (micro)blogging: shouting to a smaller
piece of the world.

Those more meaningful connections make digital communication a little less
lonely.
