#+TITLE: blog08/litreview3: NY’s 4th Grade Math, and a Sugar Project
#+TAGS: hfoss

This litreview was [[http://www.nysed.gov/common/nysed/files/programs/curriculum-instruction/nys-next-generation-mathematics-p-12-standards.pdf][New York State Next Generation Mathematics Learning Standards]]
2017, specifically the Grade 4 Math overview. As I looked at the requirements
for the curriculum, I started thinking about potential games that could aid the
curriculum. The standards cover a few different areas, each of which could be
assisted with a sugar activity.

** Geometry

Looking through shape identification and angles, the first thing that came to
mind was a Physics-like activity. Something that wasn’t a sandbox, but instead
required a drawn shape to meet certain criteria. I’m not sure how that would
implement angle measurement or angle calculation, though. That sounds tricky to
gamify.

** Fractions

I remember seeing a fractions game on display for FOSS@RIT, at the Rochester
(then Mini) Maker Faire. I think it was PyCut. In looking that up, I found a
[[https://wiki.sugarlabs.org/go/Math4Team/RIT/Projects][repo of RIT games and projects]]. I wonder if I could use those for inspiration.

A fraction game sounds fun. Either showing equality between fractions, or
building up “pieces” of a whole to equal another fraction.

But it’d be hard to top [[http://twinbeard.com/frog-fractions/][Frog Fractions]].

** Multiplication

When I was looking at that list, it reminded me of a math puzzle game I would
play when I was younger. Maybe an “adventure” game would be interesting.
Different mazes to go through, with math “roadblocks”, or something. That would
make doing simple math problems entertaining. Or, it entertained me at that age,
at least.

That game involved a big maze you would navigate, trying to reach the end. It
had different difficulty levels, and blocks along the way, where you had to do
math problems. I remember most of them being multiplication problems. I enjoyed
it, but looking back, it was pretty simple. Maybe I could spice it up? Power ups
(skip a problem, get help with a problem, etc.), catchy music, interesting
blocks in the way, and so forth.

** Lots to think about!

This leaves a lot of wiggle room, and a few questions. I’m not sure what I’d like to do, but knowing the target goals and audience is helpful. It’s also nice to have those examples. Maybe playing around a bit more with Sugar, or digging up those old games I enjoyed, will help too.
