#+TITLE: firstflight
#+TAGS: hfoss

/Note to future readers: hfoss-tagged posts are for [[https://hfoss.readthedocs.io/en/latest/][Humanitarian Free/Open Source Software Development (HFOSS) @ RIT]]/.


Most of the tasks in our introductory assignment were familiar to me: I've used
IRC, mailing lists, and git throughout the years. However, extra familiarity is
always a good thing, especially if I want to be comfortable in new development
communities!

** IRC

I've been on ~#rit-foss~ for... a while. I think I jumped on my freshman year, and
played around with clients before finally settling on Matrix.

My nick had become unregistered due to my server rebooting (I have a self-hosted
Synapse instance I run to connect to the Matrix network, +1 for
decentralization), so I had to explore reregistering my nick on Freenode through
Matrix. Thankfully the Matrix project has a solution for that:
[[https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ]]

** Mailing list

I had subscribed and posted to the public FOSSRIT mailing list before, but never
to a private mailing list. The password system provided was interesting. I like
the flexibility email has maintained throughout its lifetime: resetting your
password can be done via a website, or exclusively through email.

Sending an email to the mailing list was simple enough too! I wasn't sure it
went through at first: I believe the FOSSRIT list “echoes” emails you send back
to you. I didn't receive the one I sent, so I wasn't sure anyone else did. Turns
out, this is an available setting on the mailing list.

** A blog

You're looking at it! This baby's been set up for a couple years now, and it's
finally in a place I'm happy with.

For the curious, this is how I set it up (tldr, lots of Docker and nginx):
[[/Deploying-your-server-with-Docker-Compose/]]

** Github

I had a Github account already, and I've used Github since I started at RIT, so
I was familiar with the processing of forking, committing changes, and opening a
PR. I'm also used to YAML from working with docker-compose.
